services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server
      - ui
    networks:
      - lober
    restart: unless-stopped

  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    expose:
      - 8080
    restart: unless-stopped
    networks:
      - lober
    environment:
      - PORT=8080
      - PGHOST=db
      - PGUSER=lober
      - PGPASSWORD=lober
      - PGDATABASE=lober
      - PGSSLMODE=disable
      - MASTER_TOKEN=dev-master-token
    depends_on:
      - db

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    expose:
      - 3000
    restart: unless-stopped
    networks:
      - lober
    environment:
      - MASTER_TOKEN=dev-master-token
      - PUBLIC_MASTER_TOKEN=dev-master-token
    depends_on:
      - server

  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 15432:5432
    volumes:
      - pgdata:/var/lib/postgresql
      - ./db/init.sql:/docker-entrypoint-initdb.d/01-init.sql
    networks:
      - lober
    environment:
      - POSTGRES_USER=lober
      - POSTGRES_PASSWORD=lober
      - POSTGRES_DB=lober

volumes:
  pgdata:

networks:
  lober:
    driver: bridge